guheyo/guheyo-server

.github/ISSUE_TEMPLATE/bug_report.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
템플릿 안의 커밋 컨벤션 설명
CONTRIBUTING으로 옮겼습니다
=> docs: 템플릿 수정

.github/CODEOWNERS
매번 PR 리뷰어를 지정하는 것에 대한 번거로움
CODEOWNERS에 backend 팀 리뷰어로 자동 설정
https://help.github.com/articles/about-codeowners/
=> docs: CODEOWNERS 작성

.gitignore
=> chore: gitignore env 설정 추가

LICENSE, package.json
1. 커뮤니티에 소스 코드를 공개하기
2. 상용 목적 사용자에 의한 권리 침해로부터 보호하기
[MariaDB](https://mariadb.com/bsl-faq-mariadb/), [materialize](https://github.com/MaterializeInc/materialize/blob/main/LICENSE)의 사례를 참고하여 BUSL v1.1 라이센스 도입
https://mariadb.com/bsl-faq-adopting/#whatis
=> docs: update license to BUSL-1.1

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug_report.md, .github/dependabot.yml, CONTRIBUTING.md, LICENSE, README.md, apps/api/README.md, apps/bot/README.md, libs/core/package.json, libs/shared/package.json, package.json, src/server.ts, yarn.lock
=> feat: rename wtb to guheyo

libs/domains/package.json, libs/domains/src/user/domain/member.entity.ts, libs/domains/src/user/domain/role.entity.ts, libs/domains/src/user/domain/session.entity.ts, libs/domains/src/user/domain/social-account.entity.ts, libs/domains/src/user/domain/user.entity.ts, libs/shared/package.json, libs/shared/src/prisma/schema.prisma, libs/shared/src/prisma/seed.ts, yarn.lock
1. user domain의 aggregate 구성
2. @nestjs/swagger를 사용하기 위해서는 entity class가 필요함
- prisma는 model의 type만 return
1. user가 가입/로그인한 후에 함께 처리해야 하는 socialAccount, member, role, session을 한 aggregate로 구성
2. prisma-class-generator를 통한 entity class 생성
https://www.prisma.io/blog/nestjs-prisma-relational-data-7D056s1kOabc
https://github.com/kimjbstar/prisma-class-generator
https://github.com/typestack/class-transformer
=> feat: create user domain entity classes

libs/domains/src/user/application/port/in/member.connect-roles.usecase.ts, libs/domains/src/user/application/port/in/member.disconnect-roles.usecase.ts, libs/domains/src/user/application/port/out/member.save.port.ts, libs/domains/src/user/application/port/out/session.load.port.ts, libs/domains/src/user/application/port/out/session.save.port.ts, libs/domains/src/user/application/port/out/social-account.save.port.ts, libs/domains/src/user/application/port/out/user.load.port.ts, libs/domains/src/user/application/port/out/user.save.port.ts
1. user application의 out port class 구현
2. member에 roles을 추가 및 제거하기 위한 interface 구현
1. 각 entity 별로 out port class  정의
- CUD -> save port
- R -> load port 
2. connect roles, disconnect roles use case class 구현
=> feat: add user application out ports

apps/api/src/app/user/__tests__/user.module.spec.ts, apps/api/src/app/user/user.resolver.ts, apps/api/src/schema.gql, libs/domains/src/user/application/commands/user-create/user.create.command.ts, libs/domains/src/user/application/commands/user-delete/user.delete.command.ts, libs/domains/src/user/application/commands/user-update/user.update.command.ts, libs/domains/src/user/application/commands/user-update/user.update.input.ts
updateUser, deleteUser 구현
class-validator로 Input property 검증
- IsOptional() 활용
=> feat: add updateUser, deleteUser in resolver

apps/api/src/app/member/member.resolver.ts, apps/api/src/schema.gql, libs/domains/src/member/adapter/out/persistence/member.repository.ts, libs/domains/src/member/application/commands/connect-roles/__tests__/connect-roles.handler.spec.ts, libs/domains/src/member/application/commands/connect-roles/connect-roles.command.ts, libs/domains/src/member/application/commands/connect-roles/connect-roles.handler.ts, libs/domains/src/member/application/commands/connect-roles/connect-roles.input.ts, libs/domains/src/member/application/commands/create-member/create-member.handler.ts, libs/domains/src/member/application/commands/delete-member/delete-member.handler.ts, libs/domains/src/member/application/commands/disconnect-roles/__tests__/disconnect-roles.handler.spec.ts, libs/domains/src/member/application/commands/disconnect-roles/disconnect-roles.command.ts, libs/domains/src/member/application/commands/disconnect-roles/disconnect-roles.handler.ts, libs/domains/src/member/application/commands/disconnect-roles/disconnect-roles.input.ts, libs/domains/src/member/application/commands/member.command.module.ts, libs/domains/src/member/application/commands/update-member/update-member.handler.ts, libs/domains/src/member/application/port/out/member-roles.save.ts
Member에 role 연결 및 연결 끊기
1. command Handler 구현
2. repository, resolver 구현
=> feat: add connect-roles, disconnect-roles

libs/shared/src/prisma/migrations/20230922185417_role/migration.sql, libs/shared/src/prisma/schema.prisma
1. guild-role의 relation 변경
1. many to many -> one to many : guild-roles
=> feat: change guild-roles relation to one-to-many

apps/api/src/schema.gql, apps/bot/src/commands/upsert-roles/upsert-roles.slash-command-handler.ts, libs/domains/src/guild/adapter/out/persistence/guild.repository.ts, libs/domains/src/guild/application/commands/create-guild/create-guild.command.ts, libs/domains/src/guild/application/commands/create-guild/create-guild.input.ts, libs/domains/src/guild/application/commands/update-guild/__tests__/update-guild.handler.spec.ts, libs/domains/src/guild/application/commands/update-guild/update-guild.command.ts, libs/domains/src/guild/application/commands/update-guild/update-guild.input.ts, libs/domains/src/guild/application/dtos/guild.response.ts, libs/domains/src/guild/domain/guild.entity.ts, libs/domains/src/guild/domain/guild.types.ts, libs/domains/src/member/adapter/out/persistence/member.repository.ts, libs/domains/src/member/application/queries/find-member-by-user-and-guild/find-member-by-user-and-guild.handler.ts, libs/domains/src/role/adapter/out/persistence/role.repository.ts, libs/domains/src/role/application/commands/create-role/__tests__/create-role.handler.spec.ts, libs/domains/src/role/application/commands/create-role/create-role.command.ts, libs/domains/src/role/application/commands/create-role/create-role.input.ts, libs/domains/src/role/application/commands/update-role/__tests__/update-role.handler.spec.ts, libs/domains/src/role/application/commands/update-role/update-role.command.ts, libs/domains/src/role/application/commands/update-role/update-role.input.ts, libs/domains/src/role/application/commands/upsert-roles/__tests__/upsert-roles.handler.spec.ts, libs/domains/src/role/application/dtos/role.response.ts, libs/domains/src/role/domain/role.entity.ts, libs/domains/src/role/domain/role.types.ts, libs/domains/src/user/adapter/out/persistence/user.repository.ts, libs/shared/src/prisma/migrations/20230928220351_image/migration.sql, libs/shared/src/prisma/schema.prisma, libs/shared/src/prisma/seed.ts
1. 정규화 할 수 있는 JSON field를 model로 전환하기
2. rank -> position 이름 변경
1-1. product의 field들을 Offer, Demand, Swap, Auction의 field로 바로 넣기
1-2. Product, Post에서 Image model 분리
https://shopify.dev/docs/api/admin-rest/2023-07/resources/product#resource-object
=> feat: add image model, rename rank to position

apps/api/src/api.module.ts, apps/api/src/app/offer/__tests__/offer.module.spec.ts, apps/api/src/app/offer/offer.module.ts, apps/api/src/app/offer/offer.resolver.ts, apps/api/src/schema.gql, libs/domains/src/offer/adapter/out/persistence/offer.repository.ts, libs/domains/src/offer/application/commands/create-offer/create-offer.command.ts, libs/domains/src/offer/application/commands/create-offer/create-offer.handler.ts, libs/domains/src/offer/application/commands/create-offer/create-offer.input.ts, libs/domains/src/offer/application/commands/delete-offer/delete-offer.command.ts, libs/domains/src/offer/application/commands/delete-offer/delete-offer.handler.ts, libs/domains/src/offer/application/commands/offer.command.providers.ts, libs/domains/src/offer/application/commands/update-offer/update-offer.command.ts, libs/domains/src/offer/application/commands/update-offer/update-offer.handler.ts, libs/domains/src/offer/application/commands/update-offer/update-offer.input.ts, libs/domains/src/offer/application/dtos/offer.response.ts, libs/domains/src/offer/application/events/offer.event.providers.ts, libs/domains/src/offer/application/ports/out/offer.load.port.ts, libs/domains/src/offer/application/ports/out/offer.save.port.ts, libs/domains/src/offer/application/queries/find-offer-by-id/find-offer-by-id.handler.ts, libs/domains/src/offer/application/queries/find-offer-by-id/find-offer-by-id.query.ts, libs/domains/src/offer/application/queries/offer.query.providers.ts, libs/domains/src/offer/domain/offer.entity.ts, libs/domains/src/offer/domain/offer.error.message.ts, libs/domains/src/offer/domain/offer.types.ts, libs/domains/src/offer/offer.providers.ts, libs/shared/src/image/__tests__/image.service.spec.ts
Offer CRUD
Offer domain 정의
Offer command, query 구현
Offer resolver, module API에서 불러오기
=> feat: add offer domain

apps/bot/src/bot.module.ts, apps/bot/src/clients/clients.ts, apps/bot/src/clients/offer/offer.client.ts, apps/bot/src/clients/user-image/user-image.client.ts, apps/bot/src/clients/user/user.client.ts, apps/bot/src/events/offer-message-created/offer-message-created.handler.ts, apps/bot/src/pipes/deal/abstracts/deal.parser.ts, apps/bot/src/pipes/deal/offer/offer.error-message.ts, apps/bot/src/pipes/deal/offer/offer.parser.ts, apps/bot/src/pipes/deal/offer/offer.pipe.ts, apps/bot/src/pipes/deal/offer/offer.types.ts, apps/bot/src/pipes/parsers.ts, apps/bot/src/pipes/user/user-with-message.pipe.ts, apps/bot/src/pipes/user/user.types.ts
1. discord server에서 생성된 판매글 저장
1. user pipe로 discord user의 user data 가져오기, 없을 경우 생성
2. offer pipe로 discord message를 create offer input으로 변환
https://docs.nestjs.com/pipes
=> feat: add user client, user pipe, offer pipe

apps/bot/src/apps/deal/abstracts/deal.parser.ts, apps/bot/src/apps/offer/offer.client.ts, apps/bot/src/apps/offer/offer.parser.ts, apps/bot/src/apps/offer/offer.types.ts, apps/bot/src/apps/user-image/user-image.client.ts, apps/bot/src/apps/user-image/user-image.parser.ts, apps/bot/src/apps/user/user.client.ts, apps/bot/src/apps/user/user.parser.ts, apps/bot/src/apps/user/user.types.ts, apps/bot/src/bot.module.ts, apps/bot/src/commands/register-discord-user/register-discord-user.slash-command-handler.ts, apps/bot/src/events/discord-member-joined/discord-member-joined.handler.ts, apps/bot/src/events/offer-message-created/offer-message-created.handler.ts, apps/bot/src/pipes/offer/offer.pipe.ts, apps/bot/src/pipes/user/user-with-message.pipe.ts, apps/bot/src/pipes/user/user.pipe.ts, libs/domains/src/offer/application/commands/create-offer/create-offer.handler.ts, libs/domains/src/offer/application/commands/update-offer/update-offer.handler.ts, libs/domains/src/offer/application/events/offer-created/offer-created.event.ts, libs/domains/src/offer/application/events/offer-updated/offer-updated.event.ts, libs/domains/src/offer/application/sagas/offer.sagas.ts, libs/domains/src/offer/domain/offer.entity.ts, libs/domains/src/offer/offer.providers.ts, libs/domains/src/user/application/commands/create-user-from-discord/create-user-from-discord.handler.ts, libs/domains/src/user/application/commands/create-user/__tests__/create-user.handler.spec.ts, libs/domains/src/user/application/commands/create-user/create-user.handler.ts, libs/domains/src/user/application/commands/update-user/__tests__/user.update.handler.spec.ts, libs/domains/src/user/application/commands/update-user/update-user.handler.ts, libs/shared/src/image/image.error.message.ts, libs/shared/src/image/image.service.ts
discord에서 생성된 판매 글과 첨부 이미지 저장
1. discord에서 생성 된 message의 양식 검사 후 parsing 하여 offer 데이터로 저장
=> feat: upload and create attachments, create offer

apps/api/src/app/offer/offer.resolver.ts, apps/api/src/main.ts, apps/api/src/schema.gql, libs/domains/src/offer/application/dtos/offer.response.ts, libs/domains/src/offer/application/queries/find-offer-by-id/find-offer-by-id.handler.ts, libs/domains/src/offer/application/queries/find-offers/find-offers.args.ts, libs/domains/src/offer/application/queries/find-offers/find-offers.handler.ts, libs/domains/src/offer/application/queries/find-offers/find-offers.query.ts, libs/domains/src/offer/application/queries/find-offers/paginated-offers.response.ts, libs/domains/src/offer/application/queries/offer.query.providers.ts, libs/domains/src/user/application/dtos/user-with-members.ts, libs/shared/src/cqrs/queries/pagination/paginated.ts
1. findOffers의 결과 값으로 pagination 하기
2. offer에 userImages 포함시키기
1. PaginationArgs의 fields를 FindOffersArgs에 합침
2. type='offers' 와 refId='offer.id'로 userImages를 불러옴
=> feat: paginate offers

apps/api/src/app/social-account/social-account.resolver.ts, apps/api/src/schema.gql, libs/domains/src/social-account/adapter/out/persistence/social-account.repository.ts, libs/domains/src/social-account/application/commands/delete-social-account-by-provider/__tests__/delete-social-account-by-provider.handler.spec.ts, libs/domains/src/social-account/application/commands/delete-social-account-by-provider/delete-social-account-by-provider.command.ts, libs/domains/src/social-account/application/commands/delete-social-account-by-provider/delete-social-account-by-provider.handler.ts, libs/domains/src/social-account/application/ports/out/social-account.load.port.ts
next auth session REST -> Graphql
deleteSocialAccountByProvider 추가
=> feat: add deleteSocialAccountByProvider

apps/api/src/schema.gql, libs/domains/src/auction/application/commands/create-auction/create-auction.input.ts, libs/domains/src/auction/application/dtos/auction.response.ts, libs/domains/src/auction/application/dtos/bid.response.ts, libs/domains/src/demand/application/dtos/demand.response.ts, libs/domains/src/member/application/dtos/member.response.ts, libs/domains/src/offer/application/dtos/offer.response.ts, libs/domains/src/session/adapter/out/persistence/session.repository.ts, libs/domains/src/social-account/application/commands/delete-social-account-by-provider/__tests__/delete-social-account-by-provider.handler.spec.ts, libs/domains/src/social-account/application/dtos/social-account.without-auth.response.ts, libs/domains/src/swap/application/dtos/swap.response.ts, libs/domains/src/user-image/application/dtos/user-image.response.ts, libs/domains/src/user/adapter/out/persistence/user.repository.ts, libs/domains/src/user/application/commands/create-user/create-user.command.ts, libs/domains/src/user/application/commands/create-user/create-user.input.ts, libs/domains/src/user/application/commands/update-user/update-user.command.ts, libs/domains/src/user/application/commands/update-user/update-user.input.ts, libs/domains/src/user/application/dtos/my-user.response.ts, libs/domains/src/user/application/dtos/user.response.ts, libs/domains/src/user/domain/user.entity.ts, libs/domains/src/user/domain/user.types.ts, libs/shared/src/prisma/migrations/20240104170034_/migration.sql, libs/shared/src/prisma/schema.prisma
bid, auction: UserResponse -> AuthorResponse
User model에 name, phoneNumber field 추가
=> feat: add name, phoneNumber to User model

libs/domains/src/offer/application/queries/find-offers/find-offers.handler.ts, libs/shared/src/cqrs/queries/pagination/paginate.ts
hasNextPage 오류
hasNextPage: findMany take + 1 > take ? true : false
=> fix: hasNextPage logic in paginate

apps/api/src/app/offer/offer.resolver.ts, apps/api/src/schema.gql, libs/domains/src/auction/application/dtos/auction.response.ts, libs/domains/src/auction/application/queries/find-auctions/find-auctions.handler.ts, libs/domains/src/demand/application/dtos/demand.response.ts, libs/domains/src/demand/application/queries/find-demands/find-demands.handler.ts, libs/domains/src/swap/application/dtos/swap.response.ts, libs/domains/src/swap/application/queries/find-swaps/find-swaps.handler.ts, libs/domains/src/user/application/queries/find-users/find-users.handler.ts
cursor based pagination에서 take 처리 수정
take + 1 개를 가져온 후, hasNextPage 체크
=> fix: take in findMany

apps/api/src/app/auction/auction.resolver.ts, apps/api/src/app/demand/demand.resolver.ts, apps/api/src/app/guild/guild.resolver.ts, apps/api/src/app/offer/offer.resolver.ts, apps/api/src/app/role/role.resolver.ts, apps/api/src/app/social-account/social-account.resolver.ts, apps/api/src/app/swap/swap.resolver.ts, apps/api/src/app/user-image/user-image.resolver.ts, apps/api/src/app/user/user.resolver.ts, apps/api/src/schema.gql, libs/domains/src/demand/application/queries/demand.query.providers.ts, libs/domains/src/demand/application/queries/find-demand-by-id/find-demand-by-id.handler.ts, libs/domains/src/swap/application/queries/find-swap-by-id/find-swap-by-id.handler.ts, libs/domains/src/swap/application/queries/swap.query.providers.ts
1. id의 type이 String! 으로 설정되어 있는 문제
2. AuthorResponse의 socialAccounts 누락
1. @Args('id', { type: () => ID }
2. include socialAccounts in the buyer, proposer
=> feat: change id type to ID in query, include socialAccounts in the buyer, proposer

apps/api/src/api.module.ts, apps/api/src/app/term/term.module.ts, apps/api/src/app/term/term.resolver.ts, apps/api/src/schema.gql, libs/domains/src/term/adapter/out/persistence/term.repository.ts, libs/domains/src/term/application/domain/term.entity.ts, libs/domains/src/term/application/domain/term.error.message.ts, libs/domains/src/term/application/dtos/term.response.ts, libs/domains/src/term/application/queries/find-term/find-term.handler.ts, libs/domains/src/term/application/queries/find-term/find-term.query.ts, libs/domains/src/term/application/queries/term.query.providers.ts, libs/domains/src/term/term.providers.ts, libs/shared/src/prisma/migrations/20240123215414_terms/migration.sql, libs/shared/src/prisma/schema.prisma
policy docs DB로 관리하기
term domain 추가
term query handler, resolver 추가
=> feat: addd term domain, query handler, resolver

libs/domains/package.json, libs/shared/package.json, libs/shared/src/cqrs/queries/handlers/prisma-query.handler.ts, libs/shared/src/cqrs/repositories/prisma-repository.ts, libs/shared/src/prisma/__tests__/prisma.service.spec.ts, libs/shared/src/prisma/extensions/prisma.extension.factory.ts, libs/shared/src/prisma/extensions/soft-delete.extension.ts, libs/shared/src/prisma/prisma.module.ts, libs/shared/src/prisma/prisma.service.ts, yarn.lock
prisma version 5에서 soft delete 적용하기
prisma extension을 활용
https://www.prisma.io/docs/orm/prisma-client/client-extensions/model
https://www.prisma.io/docs/orm/prisma-client/client-extensions/query
https://github.com/prisma/prisma/issues/18628
=> feat: apply soft delete using prisma extension 

apps/bot/src/apps/user/clients/user.client.ts, apps/bot/src/apps/user/parsers/user.parser.ts, apps/bot/src/commands/register-discord-user/register-discord-user.slash-command-handler.ts, apps/bot/src/commands/upsert-roles/upsert-roles.slash-command-handler.ts, apps/bot/src/events/discord-member-roles-added/discord-member-roles-added.handler.ts, apps/bot/src/events/discord-member-roles-removed/discord-member-roles-removed.handler.ts
slash command handler에 있는 CommandBus, UserParser 제거
관련 로직 userClient로 이동
=> refactor: remove CommandBus, UserParser in slash-command handlers

apps/bot/src/commands/bulk-save/bulk-save-demands.slash-command.handler.ts, apps/bot/src/commands/bulk-save/bulk-save-offers.slash-command.handler.ts, apps/bot/src/commands/bulk-save/bulk-save-swaps.slash-command.handler.ts, apps/bot/src/commands/bulk-save/bulk-save.request.ts, apps/bot/src/commands/bulk-save/bulk-save.slash-command.handler.ts, apps/bot/src/config/config.example.yaml, apps/bot/src/shared/discord/discord.config.service.ts, apps/bot/src/shared/discord/discord.manager.ts, libs/shared/package.json, libs/shared/src/image/image.service.ts, nest-cli.json
discord.js 에서 한번에 100개 초과의 메시지를 fetch 할 수 없는 문제
1. 100개 씩 여러번 fetch 하기
2. channel 별로 메시지를 fetch 할 수 있도록 category-name 을 slash command request에 추가
https://discord.js.org/docs/packages/discord.js/main/FetchMessagesOptions:Interface
=> feat: bulk save over 100 messages using before option

apps/bot/src/apps/deal/clients/deal.client.ts, apps/bot/src/apps/user-image/clients/user-image.client.ts, apps/bot/src/apps/user/clients/user.client.ts, apps/bot/src/apps/user/parsers/user.parser.ts, apps/bot/src/events/discord-user-updated/discord-user-updated.handler.ts, apps/bot/src/events/event-handlers.ts, libs/domains/src/user/application/commands/update-user/update-user.handler.ts
1. discord에서 userAvatar가 변경될 때 avatarURL update
1. fetchSimpleUser props 으로 member 외에 user 추가
2. add DiscordUserUpdated Handler
=> feat: add DiscordUserUpdated Handler

apps/api/Dockerfile, apps/api/src/config/config.example.yaml, apps/api/src/main.ts, apps/bot/Dockerfile, apps/bot/src/commands/bulk-save/bulk-save.slash-command.handler.ts, apps/bot/src/commands/ping/ping.slash-command-handler.ts, apps/bot/src/commands/send-message/send-message.slash-command-handler.ts, apps/bot/src/events/demand-message-created/demand-message-created.handler.ts, apps/bot/src/events/demand-message-updated/demand-message-updated.handler.ts, docker-compose.yaml, libs/domains/package.json, yarn.lock
1. bulk save command에서 오류가 발생하면 멈추는 문제
2. docker-compose 변수 정리
1. bulk-save 과정에서의 오류 무시
2. arg -> env
=> fit: update dockerFile, fix slash command issues

apps/api/package.json, apps/api/src/app/auth/auth.controller.ts, apps/api/src/app/auth/auth.module.ts, apps/api/src/app/auth/auth.resolver.ts, apps/api/src/app/auth/naver/naver.strategy.ts, apps/api/src/schema.gql, libs/domains/src/social-account/application/commands/update-social-account/__tests__/update-social-account.handler.spec.ts, libs/shared/src/jwt/jwt.service.ts, package.json, yarn.lock
1. access token을 client에서 직접 접근할 수 없는 문제
2. naver 로그인 추가
1. access token은 httpOnly: false 로 설정
2. passport-naver 추가
=> feat: update cookie option in access token

apps/api/src/app/auth/auth.controller.ts, apps/api/src/app/auth/auth.resolver.ts, apps/api/src/schema.gql, libs/domains/src/demand/application/queries/find-demands/find-demands.args.ts, libs/domains/src/demand/application/queries/find-demands/find-demands.query.ts, libs/domains/src/offer/application/queries/find-offers/find-offers.args.ts, libs/domains/src/offer/application/queries/find-offers/find-offers.query.ts, libs/domains/src/swap/application/queries/find-swaps/find-swaps.args.ts, libs/domains/src/swap/application/queries/find-swaps/find-swaps.query.ts, libs/shared/src/jwt/jwt.interfaces.ts, libs/shared/src/jwt/jwt.service.ts
1. login 이후 user의 기본 정보 확인
2. find query의 where 조건 추가
1. jwtUser에 id 추가
2. find query args에 작성자 id,  status 추가
=> feat: update jwtUser, find-query-args

LICENSE, libs/domains/src/offer/application/queries/find-offer-previews/find-offers-where.args.ts, libs/shared/src/cqrs/queries/pagination/pagination-search.args.ts
GraphQLJSON 에 포함된 date 타입
string으로 변경
=> feat: change date type to string in Args

apps/api/src/api.module.ts, apps/api/src/app/report/report.module.ts, apps/api/src/app/report/report.resolver.ts, apps/api/src/schema.gql, libs/domains/src/bump/application/commands/create-bump/create-bump.input.ts, libs/domains/src/demand/application/commands/update-demand/update-demand.command.ts, libs/domains/src/demand/application/commands/update-demand/update-demand.handler.ts, libs/domains/src/demand/application/commands/update-demand/update-demand.input.ts, libs/domains/src/offer/application/commands/update-offer/update-offer.command.ts, libs/domains/src/offer/application/commands/update-offer/update-offer.handler.ts, libs/domains/src/offer/application/commands/update-offer/update-offer.input.ts, libs/domains/src/report/adapter/out/persistence/report.repository.ts, libs/domains/src/report/application/commands/create-report/create-report.command.ts, libs/domains/src/report/application/commands/create-report/create-report.handler.ts, libs/domains/src/report/application/commands/create-report/create-report.input.ts, libs/domains/src/report/application/commands/report.command.providers.ts, libs/domains/src/report/application/dtos/report.response.ts, libs/domains/src/report/application/ports/out/report.load.port.ts, libs/domains/src/report/application/ports/out/report.save.port.ts, libs/domains/src/report/application/queries/find-report/find-report.args.ts, libs/domains/src/report/application/queries/find-report/find-report.handler.ts, libs/domains/src/report/application/queries/find-report/find-report.query.ts, libs/domains/src/report/application/queries/report.query.providers.ts, libs/domains/src/report/domain/report.entity.ts, libs/domains/src/report/domain/report.error.message.ts, libs/domains/src/report/report.providers.ts, libs/domains/src/swap/application/commands/update-swap/update-swap.command.ts, libs/domains/src/swap/application/commands/update-swap/update-swap.handler.ts, libs/domains/src/swap/application/commands/update-swap/update-swap.input.ts
Report model 생성
Offer, Demand, Swap을 참조하는 Report model 생성
=> feat: add report model, domain, module

apps/api/src/app/report/report.resolver.ts, apps/api/src/schema.gql, libs/domains/src/report/application/queries/find-reports/find-reports-where.args.ts, libs/domains/src/report/application/queries/find-reports/find-reports.args.ts, libs/domains/src/report/application/queries/find-reports/find-reports.handler.ts, libs/domains/src/report/application/queries/find-reports/find-reports.order-by.args.ts, libs/domains/src/report/application/queries/find-reports/find-reports.query.ts, libs/domains/src/report/application/queries/find-reports/paginated-reports.response.ts, libs/domains/src/report/application/queries/report.query.providers.ts
report와 report-comment를 불러오는 Query
1. pagination으로 find reports 구현
=> feat: add find-reports query handler

apps/bot/src/apps/deal/parsers/abstracts/deal.parser.ts, apps/bot/src/apps/demand/parsers/demand.parser.ts, apps/bot/src/apps/offer/parsers/offer.parser.ts
discord 에서 작성된 판매, 구매 게시글의 천원 단위 가격 포함
소수 첫째짜리까지 반환
=> feat: include the first decimal place in the price

apps/api/src/app/demand/demand.resolver.ts, apps/api/src/app/offer/offer.resolver.ts, apps/api/src/app/swap/swap.resolver.ts, apps/api/src/schema.gql, libs/domains/src/demand/application/commands/bump-demand/bump-demand.handler.ts, libs/domains/src/demand/application/commands/update-demand/update-demand.handler.ts, libs/domains/src/offer/application/commands/bump-offer/bump-offer.handler.ts, libs/domains/src/offer/application/commands/update-offer/update-offer.handler.ts, libs/domains/src/swap/application/commands/bump-swap/bump-swap.handler.ts, libs/domains/src/swap/application/commands/update-swap/update-swap.command.ts, libs/domains/src/swap/application/commands/update-swap/update-swap.handler.ts, libs/domains/src/swap/application/commands/update-swap/update-swap.input.ts
1. 게시글 수정 및 끌올 후 client에서 cache update 하기
1. mutation의 return 값으로 previewResponse 반환하기
=> feat: change response of bump, update command

libs/domains/src/report/domain/report.entity.ts
ReportStatusUpdatedEvent 로 전달되는 변수 오류 수정
refVersionId -> refId
=> fix: change refVersionId to refId in reportStatusUpdatedEvent props

apps/api/src/schema.gql, libs/domains/src/user/adapter/out/persistence/user.repository.ts, libs/domains/src/user/application/commands/update-user/update-user.command.ts, libs/domains/src/user/application/commands/update-user/update-user.handler.ts, libs/domains/src/user/application/commands/update-user/update-user.input.ts, libs/domains/src/user/application/dtos/user.response.ts, libs/domains/src/user/domain/user.entity.ts, libs/domains/src/user/domain/user.types.ts, libs/shared/src/prisma/migrations/20240327112832_user_about/migration.sql, libs/shared/src/prisma/schema.prisma
유저의 소개 문구 저장
1. user model에 about field 추가
2. user domain에 about field 추가
=> feat: add about field in user model, domain

apps/api/src/app/auth/auth.controller.ts, apps/api/src/app/auth/auth.resolver.ts, libs/domains/src/auth/guards/discord/discord.strategy.ts, libs/domains/src/auth/guards/jwt/jwt-refresh.strategy.ts, libs/shared/src/jwt/jwt.interfaces.ts, libs/shared/src/jwt/jwt.service.ts, libs/shared/src/prisma/migrations/20240328000000_audit-trail-user/migration.sql
1. social profile 정보와 db의 user 정보가 UserPayload에 혼재되어 있는 문제
2. user 정보 변경 이력 조회
1. SocialPayload interface를 분리
2. create audit trail user
https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-token-claims
=> feat: add JwtPayload, SocialProfile to Jwt Interface, add audit trail user

apps/api/src/app/demand/demand.resolver.ts, apps/api/src/app/offer/offer.resolver.ts, apps/api/src/app/swap/swap.resolver.ts, apps/api/src/app/user/user.resolver.ts, apps/api/src/schema.gql, libs/domains/src/auth/decorators/auth-user/auth-user.decorator.ts, libs/domains/src/auth/decorators/extracted-jwt-payload/extracted-jwt-payload.decorator.ts, libs/domains/src/user/application/commands/link-social-profile/link-social-profile.command.ts, libs/domains/src/user/application/commands/link-social-profile/link-social-profile.handler.ts, libs/domains/src/user/application/commands/link-social-profile/link-social-profile.input.ts, libs/domains/src/user/application/commands/user.command.providers.ts
discord profile 정보로 user data 업데이트하기
1. discord oauth2로 얻은 social profile 정보를 jwt payload에 저장
2. discord profile 연동 요청시 socialProfile에 저장된 정보를 user data로 업데이트
3. 표현이 애매한 AuthUser decorator 를 ExtractedJwtPayload로 변경
=> feat: link discord profile data to user data

apps/api/src/app/auth/auth.controller.ts, apps/api/src/app/auth/auth.resolver.ts, apps/api/src/schema.gql, libs/domains/src/member/application/dtos/member-role.response.ts, libs/domains/src/member/domain/member.interfaces.ts, libs/domains/src/user/application/dtos/auth-user.response.ts, libs/domains/src/user/application/queries/find-auth-user/find-auth-user.args.ts, libs/domains/src/user/application/queries/find-auth-user/find-auth-user.handler.ts, libs/domains/src/user/application/queries/find-auth-user/find-auth-user.query.ts, libs/domains/src/user/application/queries/find-author/find-author.args.ts, libs/domains/src/user/application/queries/find-author/find-author.handler.ts, libs/domains/src/user/application/queries/find-author/find-author.query.ts, libs/domains/src/user/application/queries/user.query.providers.ts, libs/shared/src/jwt/jwt.interfaces.ts
jwtPayload에 member role 추가하기
1. MeberRoleResponse가 포함된 AuthUserResponse를 반환하여 jwt에 저장
=> feat: add member role in userPayload

apps/api/src/app/report/report.resolver.ts, libs/domains/src/auth/decorators/allowlist-role-names/allowlist-role-names.decorator.ts, libs/domains/src/auth/decorators/blocklist-role-names/blocklist-role-names.decorator.ts, libs/domains/src/auth/decorators/group-slug/group-slug.decorator.ts, libs/domains/src/auth/decorators/role-name/role-name.decorator.ts, libs/domains/src/auth/guards/naver/member-role.guard.ts, libs/domains/src/group/domain/group.constants.ts, libs/domains/src/role/domain/role.types.ts, libs/domains/src/user/application/queries/find-auth-user/find-auth-user.handler.ts
역할에 따른 신고 권한 부여
1. allowlist role names, blocklist role names decorator
2. MemberRoleGuard
3. createReport에 MeberRoleGuard 설정
=> feat: add allowlist role names, blocklist role namees, use MemberRoleGuard

apps/api/src/app/demand/demand.resolver.ts, apps/api/src/app/offer/offer.resolver.ts, apps/api/src/app/swap/swap.resolver.ts, libs/domains/src/report/domain/reported-user.entity.ts, libs/domains/src/role/domain/role.constants.ts, libs/domains/src/role/domain/role.types.ts
미답변 신고가 있는 유저의 거래글 작성, 삭제 제한
REPORTED_USER_ROLE_NAME을 blocklist로 지정
=> feat: block create, delete deal post from reported user

apps/api/src/app/member/member.resolver.ts, libs/domains/src/member/application/commands/connect-roles/connect-roles.command.ts, libs/domains/src/member/application/commands/connect-roles/connect-roles.handler.ts, libs/domains/src/member/application/commands/connect-roles/connect-roles.input.ts, libs/domains/src/member/domain/member.error.message.ts, libs/domains/src/report/application/events/checked-reported-user/checked-reported-user.event.ts, libs/domains/src/report/application/sagas/report.sagas.ts, libs/domains/src/report/domain/reported-user.entity.ts
group id 정보가 없을 때 role을 추가할 수 없는 문제
1. GroupSlug를 통해 group 찾기
2. group.id
=> feat: connect roles with group slug

apps/api/src/app/member/__tests__/member.module.spec.ts, apps/api/src/app/social-account/__tests__/social-account.module.spec.ts, apps/api/src/app/user/__tests__/user.module.spec.ts, libs/domains/src/group/application/commands/create-group/__tests__/create-group.handler.spec.ts, libs/domains/src/member/application/commands/connect-roles/__tests__/connect-roles.handler.spec.ts, libs/domains/src/user/application/queries/__tests__/user.query.module.spec.ts
test fail 고치기
1. api module에서 제외한 resolvers TestModule에서 제외
2. 변수명, 파라미터 수정
3. PrismaCommandHandler 로 extends한 handler의 test에 ConfigYamlModule, PrismaModule 주입
=> fix: solve test

libs/domains/src/demand/application/commands/bump-demand/bump-demand.handler.ts, libs/domains/src/offer/application/commands/bump-offer/bump-offer.handler.ts, libs/domains/src/swap/application/commands/bump-swap/bump-swap.handler.ts
1. 카테고리별 하루 끌올 횟수 제한
1. 거래글 생성 limit과 같이 ValidateDailyPostingLimit을 통해 제한
=> feat: validate daily bump limit

apps/bot/src/apps/user/clients/user.client.ts, apps/bot/src/commands/command-handlers.ts, apps/bot/src/commands/connect-user-roles/connect-user-roles.request.ts, apps/bot/src/commands/connect-user-roles/connect-user-roles.slash-command-handler.ts
discord member의 역할을 수동으로 connect 하기
1. connect-user-roles slash command
=> feat: add connect-user-roles slash command

apps/api/src/app/demand/demand.resolver.ts, apps/api/src/app/offer/offer.resolver.ts, apps/api/src/app/swap/swap.resolver.ts, apps/api/src/schema.gql, libs/domains/src/demand/application/queries/demand.query.providers.ts, libs/domains/src/demand/application/queries/find-demand-count/find-demand-count.args.ts, libs/domains/src/demand/application/queries/find-demand-count/find-demand-count.handler.ts, libs/domains/src/demand/application/queries/find-demand-count/find-demand-count.query.ts, libs/domains/src/discord-webhook/application/sagas/discord-webhook.sagas.ts, libs/domains/src/offer/application/queries/find-offer-count/find-offer-count.args.ts, libs/domains/src/offer/application/queries/find-offer-count/find-offer-count.handler.ts, libs/domains/src/offer/application/queries/find-offer-count/find-offer-count.query.ts, libs/domains/src/offer/application/queries/offer.query.providers.ts, libs/domains/src/swap/application/queries/find-swap-count/find-swap-count.args.ts, libs/domains/src/swap/application/queries/find-swap-count/find-swap-count.handler.ts, libs/domains/src/swap/application/queries/find-swap-count/find-swap-count.query.ts, libs/domains/src/swap/application/queries/swap.query.providers.ts
client에서 거래글 생성 전, 일일 작성 한도 체크하기
1. find offer, demand, swap count query를 통해 작성 횟수 체크
=> feat: add find deal count query handler

apps/api/src/app/report/report.resolver.ts, apps/api/src/schema.gql, libs/domains/src/report/application/queries/find-last-report/find-last-report.handler.ts, libs/domains/src/report/application/queries/find-last-report/find-last-report.query.ts, libs/domains/src/report/application/queries/report.query.providers.ts, libs/domains/src/report/domain/report.error.message.ts
1. report cooldown 체크를 위한 마지막으로 작성한 report 찾기
1. implement find last report handler
=> feat: implement find last report query handler

LICENSE, apps/bot/src/events/event-handlers.ts
#174 
offer, demand, swap message deleted event handler 비활성화
=> feat: deactive delete event handlers

apps/api/src/schema.gql, libs/domains/src/term/adapter/out/persistence/term.repository.ts, libs/domains/src/term/application/domain/term.entity.ts, libs/domains/src/term/application/dtos/term.response.ts, libs/domains/src/term/application/queries/find-term/find-term.handler.ts
term의 meta field 변경 적용
1. metaTitle, metaDescription 제거, meta 추가
=> feat: update term entity, response

apps/api/src/schema.gql, libs/domains/src/term/adapter/out/persistence/term.repository.ts, libs/domains/src/term/application/domain/term.entity.ts, libs/domains/src/term/application/dtos/term.response.ts, libs/domains/src/term/application/queries/find-term/find-term.handler.ts
=> feat: update term entity, response (#177)

apps/api/src/schema.gql, apps/bot/src/apps/demand/parsers/demand.parser.ts, apps/bot/src/apps/offer/parsers/offer.parser.ts, apps/bot/src/apps/swap/parsers/swap.parser.ts, libs/domains/src/demand/adapter/out/persistence/demand.repository.ts, libs/domains/src/demand/application/commands/create-demand/create-demand.command.ts, libs/domains/src/demand/application/commands/create-demand/create-demand.input.ts, libs/domains/src/offer/adapter/out/persistence/offer.repository.ts, libs/domains/src/offer/application/commands/create-offer/create-offer.command.ts, libs/domains/src/offer/application/commands/create-offer/create-offer.input.ts, libs/domains/src/swap/adapter/out/persistence/swap.repository.ts, libs/domains/src/swap/application/commands/create-swap/create-swap.command.ts, libs/domains/src/swap/application/commands/create-swap/create-swap.input.ts
discord server에서 bulk save할 때, 메시지 생성일이 command 실행 시간으로 잡히는 문제
1. createdAt, editedAt 값을 create input으로 가져와 저장
=> feat: add createdAt, updatedAt in create deal input

apps/api/src/main.ts
front end의 도메인 cors 허용
모든 NODE_ENV 에서 allowlist의 cors 도메인 관리
=> feat: set cors for all mode

apps/api/src/schema.gql, libs/domains/src/discord-webhook/application/sagas/discord-webhook.sagas.ts, libs/domains/src/report/application/commands/create-report/create-report.command.ts, libs/domains/src/report/application/commands/create-report/create-report.input.ts, libs/domains/src/report/domain/report.entity.ts, libs/shared/src/prisma/migrations/20240407015319_reported_user/migration.sql, libs/shared/src/prisma/schema.prisma
1. report에 reportedUserId 를 필수 값으로 설정하기
2. detail page의 slug를 짧게 줄이기
1. reportedUserId -> non nullable
2. user/[username] prefix를 지우고, offer/slug 로 단순화
=> feat: change reported user in report model to non nullable

apps/api/src/schema.gql, libs/domains/src/discord-webhook/application/sagas/discord-webhook.sagas.ts, libs/domains/src/report/application/commands/create-report/create-report.command.ts, libs/domains/src/report/application/commands/create-report/create-report.input.ts, libs/domains/src/report/domain/report.entity.ts, libs/shared/src/prisma/migrations/20240407015319_reported_user/migration.sql, libs/shared/src/prisma/schema.prisma
* feat: change reported user in report model to non nullable
=> feat: change reported user in report model to non nullable (#184)

libs/domains/src/bump/application/commands/create-bump/create-bump.input.ts, libs/domains/src/demand/application/commands/bump-demand/bump-demand.command.ts, libs/shared/src/prisma/migrations/20240407165105_deal_review_and_manner_tag/migration.sql, libs/shared/src/prisma/migrations/20240407165927_manner_tag_position/migration.sql, libs/shared/src/prisma/migrations/20240407200000_audit-deal-review/migration.sql, libs/shared/src/prisma/schema.prisma, libs/shared/src/prisma/seeds/manner-tags/seed-manner-tags.ts, libs/shared/src/prisma/seeds/seed.ts
거래 후기 및 매너 태그 스키마 생성
1. DealReview model
2. MannerTag model
=> feat: add deal-review, manner-tag in schema

apps/api/src/app/report/report.resolver.ts, apps/api/src/schema.gql, libs/domains/src/comment/application/commands/update-comment/update-comment.command.ts, libs/domains/src/comment/application/commands/update-comment/update-comment.input.ts, libs/domains/src/group/application/queries/find-group-previews/find-group-previews.handler.ts, libs/domains/src/report/adapter/out/persistence/report.repository.ts, libs/domains/src/report/application/commands/comment-report/comment-report.handler.ts, libs/domains/src/report/application/commands/report.command.providers.ts, libs/domains/src/report/application/commands/update-report-comment/update-report-comment.command.ts, libs/domains/src/report/application/commands/update-report-comment/update-report-comment.handler.ts, libs/domains/src/report/application/commands/update-report-comment/update-report-comment.input.ts, libs/domains/src/report/application/dtos/report-comment.response.ts, libs/domains/src/report/application/dtos/report.response.ts, libs/domains/src/report/application/ports/out/report.save.port.ts, libs/domains/src/report/application/queries/find-report-comment/find-report-comment.args.ts, libs/domains/src/report/application/queries/find-report-comment/find-report-comment.handler.ts, libs/domains/src/report/application/queries/find-report-comment/find-report-comment.query.ts, libs/domains/src/report/application/queries/report.query.providers.ts, libs/domains/src/report/application/sagas/report.sagas.ts, libs/domains/src/report/domain/report.entity.ts, libs/domains/src/report/domain/report.error.message.ts
신고 댓글을 기존 comment에서 report comment로 변경
1. Report Comment Entity
2. Create, Update report comment
3. return report comment response
=> feat: add report comment response, update report comment handler

libs/domains/src/offer/application/events/offer-updated/offer-updated.event.ts, libs/domains/src/offer/application/sagas/offer.sagas.ts, libs/domains/src/offer/domain/offer.entity.ts, libs/domains/src/post/adapter/out/persistence/post.repository.ts, libs/domains/src/post/application/commands/post.command.providers.ts, libs/domains/src/post/application/commands/update-thumbnail/update-thumbnail.command.ts, libs/domains/src/post/application/commands/update-thumbnail/update-thumbnail.handler.ts, libs/domains/src/post/application/commands/update-thumbnail/update-thumbnail.input.ts, libs/domains/src/post/domain/post.entity.ts
offer 생성 및 수정 후 thumbnail update
1. update thumbnail handler
2. send update thumbnail command in offer sagas
=> feat: update thumbnail of post after create, update offer

libs/domains/src/discord-webhook/application/sagas/discord-webhook.sagas.ts, libs/domains/src/user-review/adapter/out/persistence/user-review.repository.ts, libs/domains/src/user-review/application/commands/check-other-user-review/check-other-user-review.command.ts, libs/domains/src/user-review/application/commands/check-other-user-review/check-other-user-review.handler.ts, libs/domains/src/user-review/application/commands/check-other-user-review/check-other-user-review.input.ts, libs/domains/src/user-review/application/commands/create-user-review/create-user-review.handler.ts, libs/domains/src/user-review/application/events/user-review-created/user-review-created.event.ts, libs/domains/src/user-review/application/events/user-review-created/user-review-created.input.ts, libs/domains/src/user-review/application/ports/out/user-review.load.port.ts, libs/domains/src/user-review/application/sagas/user-review.sagas.ts, libs/domains/src/user-review/domain/user-review.entity.ts, libs/domains/src/user-review/domain/user-review.error.message.ts
1.UserReviewCreatedEvent의 불필요한 fields 제거
2. webhook 메시지의 offer url 변경
1. id, status만 남기기
2. businessFunction/offerId -> offer/offerId
=> feat: reduce fields in UserReviewCreatedEvent

apps/api/src/app/comment/comment.resolver.ts, apps/api/src/schema.gql, libs/domains/src/comment/application/commands/comment.command.providers.ts, libs/domains/src/comment/application/commands/create-comment/create-comment.command.ts, libs/domains/src/comment/application/commands/create-comment/create-comment.handler.ts, libs/domains/src/comment/application/commands/create-comment/create-comment.input.ts, libs/domains/src/comment/application/commands/delete-comment/delete-comment.command.ts, libs/domains/src/comment/application/commands/delete-comment/delete-comment.handler.ts, libs/domains/src/comment/application/commands/delete-comment/delete-comment.input.ts, libs/domains/src/comment/application/dtos/delete-comment.result.ts, libs/domains/src/comment/application/queries/comment.query.providers.ts, libs/domains/src/comment/application/queries/find-comments/find-comments-order-by.args.ts, libs/domains/src/comment/application/queries/find-comments/find-comments-where.args.ts, libs/domains/src/comment/application/queries/find-comments/find-comments.args.ts, libs/domains/src/comment/application/queries/find-comments/find-comments.handler.ts, libs/domains/src/comment/application/queries/find-comments/find-comments.query.ts, libs/domains/src/comment/application/queries/find-comments/paginated-comments.response.ts, libs/domains/src/report/application/queries/find-report-previews/find-report-previews-where.args.ts, libs/domains/src/report/application/queries/find-report-previews/find-report-previews.handler.ts, libs/domains/src/user/application/queries/find-author/find-author.handler.ts
1. find comments
2. delete comment
1. find comments query, handler
2. delete comment command, handler
=> feat: add find comments handler, delete comment handler

libs/domains/src/group/application/queries/find-group-previews/find-group-previews.handler.ts, libs/shared/src/prisma/migrations/20240502164145_reaction_emoji/migration.sql, libs/shared/src/prisma/migrations/20240502164146_audit_trail_reaction_emoji/migration.sql, libs/shared/src/prisma/migrations/20240502175325_custom_emoji/migration.sql, libs/shared/src/prisma/schema.prisma, libs/shared/src/prisma/seeds/emojis/seed-emojis.ts, libs/shared/src/prisma/seeds/seed.ts
게시글, 댓글에 반응할 이모지 model 설계
1. emoji - custom, default -> isCustom으로 구분
2. reaction - post, comment <-> emoji
=> feat: add emoji, reaction in prisma.schema

apps/api/src/api.module.ts, apps/api/src/app/emoji/emoji.module.ts, apps/api/src/app/emoji/emoji.resolver.ts, apps/api/src/schema.gql, libs/domains/src/emoji/application/dtos/emoji.response.ts, libs/domains/src/emoji/application/queries/emoji.query.providers.ts, libs/domains/src/emoji/application/queries/find-emojis/find-emojis.args.ts, libs/domains/src/emoji/application/queries/find-emojis/find-emojis.handler.ts, libs/domains/src/emoji/application/queries/find-emojis/find-emojis.query.ts, libs/domains/src/emoji/emoji.providers.ts, libs/shared/src/prisma/migrations/20240503190434_emoji_position/migration.sql, libs/shared/src/prisma/schema.prisma, libs/shared/src/prisma/seeds/emojis/seed-emojis.ts
client에서 emoji 목록 불러오기
1. emoji response
2. find emojis query handler
3. emoji resolver, module
=> feat: add find emojis query handler

apps/api/package.json, apps/api/src/api.module.ts, apps/api/src/app/comment/comment.resolver.ts, apps/api/src/main.ts, apps/api/src/schema.gql, libs/domains/src/comment/application/commands/create-comment/create-comment.handler.ts, libs/domains/src/post/application/dtos/post-with-reactions.response.ts, libs/domains/src/reaction/application/dtos/reaction.response.ts, libs/domains/src/user-review/application/queries/find-user-review/find-user-review.handler.ts, libs/shared/package.json, libs/shared/src/pubsub/graphql-pub-sub.ts, libs/shared/src/serializer-interceptor/global-serializer-interceptor.ts, yarn.lock
1. 새 댓글 업데이트 정보 client로 전달하기
2. subscription response가 ClassSerializerInterceptor 처리에서 오류 뜨는 문제
1-1. graphql-ws
1-2. graphql subscription - commentCreated
1-3. GraphqlPubSub - publish, asyncIterator
2. intercept에서 subscription 필터링
https://docs.nestjs.com/graphql/subscriptions
https://github.com/nestjs/graphql/issues/438
=> feat: add subscription commentCreated

apps/api/src/schema.gql, apps/bot/src/apps/bot.providers.ts, apps/bot/src/apps/group/clients/group.client.ts, apps/bot/src/apps/group/parsers/group.parser.ts, apps/bot/src/apps/group/pipes/parse-group.pipe.ts, apps/bot/src/apps/user-review/clients/user-review.client.ts, apps/bot/src/apps/user-review/parsers/user-review.parser.ts, apps/bot/src/apps/user-review/user-review.providers.ts, apps/bot/src/bot.module.ts, apps/bot/src/commands/bulk-save/bulk-save-buys.slash-command.handler.ts, apps/bot/src/commands/bulk-save/bulk-save-offers.slash-command.handler.ts, apps/bot/src/commands/bulk-save/bulk-save-posts.slash-command.handler.ts, apps/bot/src/commands/bulk-save/bulk-save-sells.slash-command.handler.ts, apps/bot/src/commands/bulk-save/bulk-save-swaps.slash-command.handler.ts, apps/bot/src/commands/bulk-save/bulk-save-user-reviews.slash-command.handler.ts, apps/bot/src/commands/command-handlers.ts, apps/bot/src/shared/discord/discord.config.service.ts, apps/bot/src/shared/discord/discord.manager.ts, apps/bot/src/shared/interfaces/post-message.interfaces.ts, libs/domains/src/post/application/commands/create-post/create-post.input.ts, libs/domains/src/user-review/adapter/out/persistence/user-review.repository.ts
1. discord forum 채널에 있는 message 데이터 불러오기
2. post message를 user review로 parsing 하기
1-1. fetchPostMessagesFromForum
1-2. fetchPostMessageFromThreadChannel
2-1. user review parser
2-2. user review client
2-3. BulkSavePostsSlashCommandHnadler
2-4. BulkSaveUserReviewsSlashCommandHnadler
https://discord.js.org/docs/packages/discord.js/14.15.2/ForumChannel:Class#threads
https://discord.js.org/docs/packages/discord.js/14.15.2/GuildForumThreadManager:Class#fetch
https://discord.js.org/docs/packages/discord.js/14.15.2/ThreadChannel:Class#messages
=> feat: fetch user reviews from discord forum channel

apps/bot/src/apps/bot.providers.ts, apps/bot/src/apps/post/clients/post.client.ts, apps/bot/src/apps/post/parsers/post.parser.ts, apps/bot/src/apps/post/post.proviers.ts, apps/bot/src/commands/bulk-save/bulk-save-posts.slash-command.handler.ts, apps/bot/src/shared/discord/discord.manager.ts, libs/domains/src/post/application/quries/check-user-posts-not-exist/check-posts-not-exist.args.ts, libs/domains/src/post/application/quries/check-user-posts-not-exist/check-posts-not-exist.handler.ts, libs/domains/src/post/application/quries/check-user-posts-not-exist/check-posts-not-exist.query.ts, libs/domains/src/post/application/quries/post.query.providers.ts
1. bulk-save-user-reviews에서 이미 생성된 거래 후기를 다시 생성하는 문제
2. threads.fetch 에서 archived 된 threads가 모두 fetch 되지 않는 문제
1. CheckPostsNotExistQuery handler를 통해 nonExistingPostIds를 가져온 후, bulk-save 실행
2. threads.fetchArchived 에 before, limit options을 통해 오래된 threadChannels을 모두 불러오기
https://discord.js.org/docs/packages/discord.js/14.15.2/GuildForumThreadManager:Class#fetch
=> feat: fetch archived threads, add CheckPostsNotExistQuery handler

apps/api/src/config/config.example.yaml, libs/domains/src/discord-webhook/application/commands/send-discord-webhook/send-discord-webhook.command.ts, libs/domains/src/discord-webhook/application/commands/send-discord-webhook/send-discord-webhook.handler.ts, libs/domains/src/discord-webhook/application/sagas/discord-webhook.sagas.ts, libs/domains/src/report/application/commands/create-report/create-report.handler.ts, libs/domains/src/report/application/events/report-created/report-created.event.ts, libs/domains/src/report/application/events/report-created/report-created.input.ts, libs/domains/src/report/domain/report.entity.ts, libs/domains/src/report/domain/report.error.message.ts, libs/domains/src/report/domain/reported-user.entity.ts, libs/domains/src/user-review/application/events/user-review-created/user-review-created.event.ts, libs/domains/src/user-review/application/events/user-review-created/user-review-created.input.ts, libs/domains/src/user-review/domain/user-review.entity.ts, libs/shared/src/discord/discord-webhook.service.ts
1. report 생성 웹훅 발송
2. userReview 생성 웹훅 발송
1. 여러 채널의 웹훅 발송을 위해 webhook -> webhookClients 으로 변경
2. reportCreatedEvent -> SendDiscordWebhookCommand
2. userReviewCreatedEvent -> SendDiscordWebhookCommand
=> feat: add reportCreated, userReviewCreated in DiscordWebhookSagas

.gitignore, libs/shared/package.json, libs/shared/src/prisma/schemas/schema-v0.2.0.prisma, libs/shared/src/prisma/schemas/schema-v0.3.0.prisma, libs/shared/src/prisma/scripts/migrate-to-v0.3.0.ts
v0.2.0 schema의 data를 v0.3.0 schema로 migration
1. schema-v0.2.0.prisma, schema-v0.3.0.prisma 두 개로 분리
2. migrate script로 변경된 데이터를 옮기기
=> feat: new post model migration

.eslintignore, apps/bot/src/events/sell-message-deleted/sell-message-deleted.handler.ts, libs/domains/src/auction/adapter/out/persistence/auction.repository.ts, libs/domains/src/bump/adapter/out/persistence/bump.repository.ts, libs/domains/src/comment/adapter/out/persistence/comment.repository.ts, libs/domains/src/comment/application/commands/create-comments/create-comments.handler.ts, libs/domains/src/comment/domain/comment.error.message.ts, libs/domains/src/group/adapter/out/persistence/group.repository.ts, libs/domains/src/offer/adapter/out/persistence/offer.repository.ts, libs/domains/src/post/adapter/out/persistence/post.repository.ts, libs/domains/src/reaction/adapter/out/persistence/reaction.repository.ts, libs/domains/src/report/adapter/out/persistence/report.repository.ts, libs/domains/src/role/adapter/out/persistence/role.repository.ts, libs/domains/src/social-account/adapter/out/persistence/social-account.repository.ts, libs/domains/src/tag/adapter/out/persistence/tag.repository.ts, libs/domains/src/term/adapter/out/persistence/term.repository.ts, libs/domains/src/user-image/adapter/out/persistence/user-image.repository.ts, libs/domains/src/user-review/adapter/out/persistence/user-review.repository.ts, libs/domains/src/user/adapter/out/persistence/user.repository.ts, libs/domains/src/version/adapter/out/persistence/version.repository.ts
1. repository의 create many에서의 error handling
2. comment.postId에 해당하지 않는 post가 존재하지 않을 떄의 comment 생성 에러 처리
1. Promise.all 을 통한 전체 error handling
2. Post 존재 여부 확인 후, 없을 경우 Post not found exception throw
=> feat: handling exception in create many

libs/domains/src/comment/application/commands/create-comments/create-comments.handler.ts
post를 찾을 때 postId가 아닌 comment.id가 들어간 문제
id -> postId
=> fix: change id to postId

.eslintignore, apps/bot/src/events/sell-message-deleted/sell-message-deleted.handler.ts, libs/domains/src/auction/adapter/out/persistence/auction.repository.ts, libs/domains/src/bump/adapter/out/persistence/bump.repository.ts, libs/domains/src/comment/adapter/out/persistence/comment.repository.ts, libs/domains/src/comment/application/commands/create-comments/create-comments.handler.ts, libs/domains/src/comment/domain/comment.error.message.ts, libs/domains/src/group/adapter/out/persistence/group.repository.ts, libs/domains/src/offer/adapter/out/persistence/offer.repository.ts, libs/domains/src/post/adapter/out/persistence/post.repository.ts, libs/domains/src/reaction/adapter/out/persistence/reaction.repository.ts, libs/domains/src/report/adapter/out/persistence/report.repository.ts, libs/domains/src/role/adapter/out/persistence/role.repository.ts, libs/domains/src/social-account/adapter/out/persistence/social-account.repository.ts, libs/domains/src/tag/adapter/out/persistence/tag.repository.ts, libs/domains/src/term/adapter/out/persistence/term.repository.ts, libs/domains/src/user-image/adapter/out/persistence/user-image.repository.ts, libs/domains/src/user-review/adapter/out/persistence/user-review.repository.ts, libs/domains/src/user/adapter/out/persistence/user.repository.ts, libs/domains/src/version/adapter/out/persistence/version.repository.ts
1. create many에서 오류 발생시 에러 처리가 안되는 문제
2. post를 찾을 때 잘못 전달된 변수
1. map -> Promise.all
2. id -> postId
=> feat: handle error in create many, fix args in find post

apps/api/src/app/user-review/user-review.resolver.ts, apps/api/src/schema.gql, libs/domains/src/user-review/application/commands/deal-review.command.providers.ts, libs/domains/src/user-review/application/commands/delete-user-review/delete-user-review.args.ts, libs/domains/src/user-review/application/commands/delete-user-review/delete-user-review.command.ts, libs/domains/src/user-review/application/commands/delete-user-review/delete-user-review.handler.ts, libs/domains/src/user-review/application/commands/user-review.command.providers.ts, libs/domains/src/user-review/domain/user-review.entity.ts, libs/domains/src/user-review/user-review.providers.ts
거래 후기 삭제
1. DeleteUserReview Command handler
2. DeleteUserReview mutation in resolver
=> feat: add delete user review handler

apps/api/src/app/user-review/user-review.resolver.ts, apps/api/src/schema.gql, libs/domains/src/user-review/application/commands/deal-review.command.providers.ts, libs/domains/src/user-review/application/commands/delete-user-review/delete-user-review.args.ts, libs/domains/src/user-review/application/commands/delete-user-review/delete-user-review.command.ts, libs/domains/src/user-review/application/commands/delete-user-review/delete-user-review.handler.ts, libs/domains/src/user-review/application/commands/user-review.command.providers.ts, libs/domains/src/user-review/domain/user-review.entity.ts, libs/domains/src/user-review/user-review.providers.ts
* feat: add delete user review command handler
* feat: add DeleteUserReviewHandler in providers
* feat: add delteUserReview in resolver
=> feat: add delete user review handler (#230)
